version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - beemonitor-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - postgres
    env_file: 
      - .env
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - beemonitor-network

  beemonitor-backend:
    image: edsonisaac/beemonitor-backend:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - pgadmin
    env_file: 
      - .env
    ports:
      - "8080:8080"
    volumes:
      - beemonitor-backend-data:/var/lib/beemonitor-backend
    networks:
      - beemonitor-network
  
  beemonitor-frontend:
    image: edsonisaac/beemonitor-frontend:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - pgadmin
      - beemonitor-backend
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - beemonitor-frontend-data:/var/lib/beemonitor-frontend
    networks:
      - beemonitor-network

volumes:
  postgres-data:
  pgadmin-data:
  beemonitor-backend-data:
  beemonitor-frontend-data:

networks:
  beemonitor-network:
    driver: bridge