version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - beemonitor-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - postgres
    env_file: 
      - .env
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - beemonitor-network

  beemonitor:
    image: edsonisaac/beemonitor-backend:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - pgadmin
    env_file: 
      - .env
    ports:
      - "8080:8080"
    volumes:
      - beemonitor-data:/var/lib/beemonitor
    networks:
      - beemonitor-network
    
volumes:
  postgres-data:
  pgadmin-data:
  beemonitor-data:

networks:
  beemonitor-network:
    driver: bridge