jwt:
  expiration: 43200000
  secret: bcL4GKuunKN-kV+_?W##=STAx#<k'3uFJ;rL-MnF>t:~)XTSBZ>$H'eM1=@.70{NWY

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: beemonitor
    url: jdbc:h2:file:./data/database/database-development
    username: beemonitor
  h2:
    console:
      enabled: true
      path: /database/h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    locale: pt_BR