jwt:
  expiration: 43200000
  secret: bcL4GKuunKN-kV+_?W##=STAx#<k'3uFJ;rL-MnF>t:~)XTSBZ>$H'eM1=@.70{NWY

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: beemonitor
    username: beemonitor
    url: jdbc:h2:mem:database-test
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    locale: pt_BR