app:
  security:
    rsa:
      public-key: classpath:certs/jwt/public.pem
      private-key: classpath:certs/jwt/private.pem

server:
  ssl:
    enabled: true
    certificate: classpath:certs/ssl/certificate.crt
    certificate-private-key: classpath:certs/ssl/private.key

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beemonitor
    username: beemonitor
    password: beemonitor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    locale: pt_BR

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui