jwt:
  expiration: 43200000
  secret: bcL4GKuunKN-kV+_?W##=STAx#<k'3uFJ;rL-MnF>t:~)XTSBZ>$H'eM1=@.70{NWY

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: beemonitor
    url: jdbc:postgresql://localhost/beemonitor-development
    username: beemonitor
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false